### ISSUE TITLE
Wrong detection of Intersected Indexes

### ISSUE THREAD

**Issue by SButterfly** [mfvanek/pg-index-health#69] opened 2020-03-21 08:51 UTC
```
create table test_table (
    id bigserial primary key,
    key bigint not null
);
create index indx on test_table(id, key);
```
Will fail on intersected indexes:
`indx` and `test_table_pkey`

How should I resolve this issue?

**Comment by kondratyev-nv** [comment] 2020-03-21 11:08
@SButterfly Thank you for the issue! However, it looks like this is a duplicate of #66.

**Comment by mfvanek** [comment] 2020-03-23 05:49
> How should I resolve this issue?

`drop index concurrently if exists indx;`

Any composite index containing a primary key column looks extremely suspicious. This makes sense if you are making a partial index, but in your case the index will be useless.
The fact is that the primary key uniquely addresses an entry in the table, so it is sufficient to search for equality. All other filter conditions can be effectively processed without an additional index.

**Closed** 2020-03-23 05:49 UTC
Labels: duplicate
